Send To Manager Review Now Making Use of CompanyReviewers Table
BiblioNexusStudio/aquifer-server pull request #401
Opened 2024-08-21 15:26 UTC by carlosmorales125

2024-08-21 15:28 UTC, MrGrinst commented on src/Aquifer.Data/Entities/UserEntity.cs
> +    public ICollection<CompanyReviewerEntity> CompanyReviewers { get; set; } = [];
Do we need this here? Doesn't look like it's being referenced anywhere.

2024-08-21 15:29 UTC, jwinston-bn commented on src/Aquifer.Data/Entities/CompanyReviewerEntity.cs
> +    [ForeignKey(nameof(UserId))]
Don't think we need these attributes.

2024-08-21 17:04 UTC, MrGrinst approved these changes

2024-08-21 17:09 UTC, MrGrinst requested changes
Could you also remove the DefaultReviewerUser stuff from CompanyEntity? We don't want to do the migration to remove the column in this PR, but it would be nice to deploy the change that removes code-level references alongside this.

2024-08-21 17:30 UTC, jwinston-bn commented
> Could you also remove the DefaultReviewerUser stuff from CompanyEntity? We don't want to do the migration to remove the column in this PR, but it would be nice to deploy the change that removes code-level references alongside this.

Doesn't that impact the foreign key relationship though, and by removing it, wouldn't that generate a change in the migration file?

2024-08-21 17:33 UTC, MrGrinst commented
> > Could you also remove the DefaultReviewerUser stuff from CompanyEntity? We don't want to do the migration to remove the column in this PR, but it would be nice to deploy the change that removes code-level references alongside this.
> 
> Doesn't that impact the foreign key relationship though, and by removing it, wouldn't that generate a change in the migration file?

It would only affect the migrations if we ran the migration add command. But to avoid the 500s we got last time we removed a column I think we need to remove the code-level reference in one PR, then do the migration in a separate PR.

2024-08-21 17:52 UTC, MrGrinst commented
> Yeah, I'm struggling to think of what the ordering should be here. It doesn't feel right for an entity to be in prod that doesn't align with what's in the database. Is your suggestion to also remove `DefaultReviewerUserId` from CompanyEntity now as well?

Yeah we would remove both of them, I should've been clearer but that was my suggestion to remove `DefaultReviewerUserId` and `DefaultReviewerUser`. And the entity will only be in prod for a very short duration before we would deploy the migration to remove the column.

2024-08-21 18:07 UTC, jwinston-bn commented
All right. I think that's fine. So my suggestion would be to remove it now, and then have a follow-up PR ready to go up to prod with the migration to deploy immediately after the first goes up.

2024-08-22 13:03 UTC, jwinston-bn approved these changes

2024-08-22 14:05 UTC, MrGrinst approved these changes

2024-08-22 14:15 UTC, merged